[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "poseidon_viz"
version = "0.1.0"
description = ""
authors = ["Panos Mavrogiorgos <pmav99@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pyproj = "^3.0.0"
holoviews = "^1.14.0"
numpy = "^1.19.4"
pandas = "^1.1.5"
bokeh = "^2.2.3"
panel = "^0.10.2"
typer = "^0.3.2"
xarray = "^0.16.2"
netCDF4 = "^1.5.5"
scipy = "^1.5.4"
datashader = "^0.11.1"
matplotlib = "^3.3.3"
llvmlite = "<=0.34"
notebook = "^6.2.0"
jupyter = "^1.0.0"
jupyter-server-proxy = "^1.5.3"
geoviews = "^1.8.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
nodeenv = "^1.5.0"

[tool.poetry.scripts]
pv = "poseidon_viz.cli:app"

[tool.black]
line-length = 129
target-version = ['py38']
